### ISSUE TITLE
Question: Does it support loading a ZTS interpreter from NTS environments?

### ISSUE THREAD

**Issue by sj-i** [adsr/php-meta-sapi#1]
Just out of curiosity.

If so, it would be interesting, as it would enable add-ons of multi-threading extensions like parallel to ordinary NTS environments, once the distribution hassles are addressed.

**Comment by adsr** [comment]
Hi @sj-i, good question. Yes, it seems to work as long as `php_tsrm_startup` is invoked before running the meta SAPI:

https://gist.github.com/adsr/6df58982eaf21cf5a8f85683158d5de1

```
adam@ap8h61:~/php-meta-sapi$ ./php-meta-sapi.php --libphp-path ~/php-src/.libs/libphp.so
PHP 8.4.0-dev sapi=cli zts=0
php_meta_sapi > printf("PHP %s sapi=%s zts=%d\n", PHP_VERSION, PHP_SAPI, PHP_ZTS);
PHP 8.4.0-dev sapi=meta zts=1
php_meta_sapi > ^C
```

Good idea about using ZTS extensions from NTS. I will mention it in the README.

**Comment by sj-i** [comment]
Hi @adsr, thanks for the answer! It's a really impressive experiment!
